docker_swarm_watcher: docker-swarm-watcher -c "echo '\n ====> Watcher event <====' && /app/comsave/after_docker_service_event.sh" -s "unix:///tmp/docker.sock" -e "service:create,service:remove,service:update"
# docker_swarm_watcher: docker-swarm-watcher -c "/app/comsave/after_docker_service_event.sh" -s "unix:///tmp/docker.sock" -e "service:create,service:remove,service:update"
nginx: nginx
